
# Broadcasting and vectorized operations

In [13]:
import numpy as np
import sys

In [4]:
a= np.arange(4)

In [5]:
a

array([0, 1, 2, 3])

In [6]:
a+10 #any operation performed like this do not modify original array but return a new array

array([10, 11, 12, 13])

In [7]:
a*10

array([ 0, 10, 20, 30])

In [8]:
a

array([0, 1, 2, 3])

In [11]:
a+=100        #modify original array

In [12]:
a

array([110, 111, 112, 113])

In [13]:
l= [0, 1, 2, 3]

In [14]:
[i*10 for i in l]

[0, 10, 20, 30]

In [15]:
a=np.arange(4)

In [16]:
a

array([0, 1, 2, 3])

In [20]:
b= np.array([10, 10, 10, 10])

In [21]:
b

array([10, 10, 10, 10])

In [22]:
a+b

array([10, 11, 12, 13])

In [24]:
a*b

array([ 0, 10, 20, 30])

# Boolean Arrays

In [25]:
#boolean opeartors returns boolean arrays that can be used for filtering
a= np.arange(4)

In [26]:
a

array([0, 1, 2, 3])

In [27]:
a[[0, -1]]

array([0, 3])

In [28]:
a[0], a[1]

(0, 1)

In [31]:
a[[True, False, False, True]]

array([0, 3])

In [32]:
a

array([0, 1, 2, 3])

In [33]:
a>=2

array([False, False,  True,  True])

In [34]:
a[a>=2]

array([2, 3])

In [35]:
a.mean()

1.5

In [36]:
a[a>a.mean()]

array([2, 3])

In [38]:
a[~(a>a.mean())]

array([0, 1])

In [39]:
a[(a==0)|(a==1)]

array([0, 1])

In [40]:
a[(a<=2)&(a%2==0)]

array([0, 2])

In [41]:
A= np.random.randint(100, size=(3,3))

In [42]:
A

array([[29,  2, 18],
       [82,  8, 21],
       [60, 51, 47]])

In [43]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([29, 18,  8, 60, 47])

In [47]:
A>30

array([[False, False, False],
       [ True, False, False],
       [ True,  True,  True]])

In [48]:
A[[A>30]]

C:\Users\Anshita\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([82, 60, 51, 47])

# Linear Algebra

In [3]:
A= np.array([
    [1,2,3], 
    [4,5,6], 
    [7,8,9]
])

In [4]:
B= np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [5]:
A.dot(B)          #dot product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [11]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [6]:
B.T             #transpose

array([[6, 4, 2],
       [5, 3, 1]])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
B.T@A

array([[36, 48, 60],
       [24, 33, 42]])

In [10]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

# Size of objects in memory

## Int, Floats

In [14]:
#An integer in python >24bytes
sys.getsizeof(1)

28

In [15]:
#Longs are even larger
sys.getsizeof(10**100)

72

In [16]:
#Numpy size is much smaller
np.dtype(int).itemsize

4

In [17]:
np.dtype(float).itemsize

8

## Lists are even larger

In [18]:
# A one-element list
sys.getsizeof([1])

72

In [19]:
#An array of one element in numpy
np.array([1]).nbytes

4

## And performance is also important 

In [24]:
l= list(range(100000))

In [31]:
a= np.arange(100000)

In [34]:
%time np.sum(a**2)

Wall time: 0 ns


216474736

In [33]:
%time sum([x**2 for x in l])

Wall time: 104 ms


333328333350000

# Useful Numpy Functions

## random

In [35]:
np.random.random(size =2)

array([0.31995097, 0.67819655])

In [36]:
np.random.normal(size =2)

array([-0.80239177, -1.06579982])

In [37]:
np.random.rand(2, 4)

array([[0.28572723, 0.45693669, 0.32778512, 0.89912266],
       [0.04402005, 0.86162221, 0.3701333 , 0.16025116]])

## arange

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [40]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## reshape 

In [41]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## linspace

In [45]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [47]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [48]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## zeros, ones empty 

In [49]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.zeros((3,3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [55]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

## Identity and eye

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [62]:
"Hello world"[6]

'w'