In [ ]:
import sys
import numpy as np

# Basic Numpy Array

In [3]:
a= np.array([1,2,3,4])

In [4]:
b= np.array([0, 0.5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[1], b[-1]

(0.0, 0.5, 2.0)

In [12]:
b[[0, 2, -1]]                    #create new numpy array

array([0., 1., 2.])

# Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('float64')

In [16]:
np.array([1,2,3,4], dtype= np.float)

array([1., 2., 3., 4.])

In [17]:
np.array([1,2,3,4], dtype= np.int8)

array([1, 2, 3, 4], dtype=int8)

In [18]:
c= np.array(['a', 'b', 'c'])

In [19]:
c.dtype

dtype('<U1')

In [20]:
d= np.array([{'a':1}, sys])

In [21]:
d.dtype              #array of type object

dtype('O')

# Shapes and dimensions

In [22]:
A= np.array([[1,2,3], 
            [4,5,6]])

In [23]:
A.shape

(2, 3)

In [24]:
A.ndim

2

In [25]:
A.size

6

In [26]:
B= np.array([
            [
                [1,2,3], 
                [4,5,6]
            ], 
            [
                [1,2,3], 
                [4,5,6]
            ],
            ])

In [27]:
B.shape

(2, 2, 3)

In [28]:
B.size

12

In [29]:
B.ndim

3

# Indexing and slicing of matrices

In [38]:
A= np.array([
    [1,2,3],
    [4,5,6], 
    [7,8,9]
])

In [39]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
A[1]

array([4, 5, 6])

In [41]:
A[1][0]

4

In [42]:
A[1, 0]

4

In [43]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [45]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [46]:
A[:2, 2:]

array([[3],
       [6]])

In [47]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
A[1]= np.array([10, 10, 10])

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [50]:
A[2]= 99

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Statistics

In [52]:
a= np.array([1, 2, 3, 4])

In [53]:
a.sum()

10

In [54]:
a.mean()

2.5

In [55]:
a.std()

1.118033988749895

In [56]:
a.var()

1.25

In [57]:
A= np.array([
    [1,2,3],
    [4,5,6], 
    [7,8,9]
])

In [58]:
A.sum()

45

In [59]:
A.mean()

5.0

In [60]:
A.std()

2.581988897471611

In [61]:
A.var()

6.666666666666667

In [62]:
A.sum(axis =0)     #coloumnwise 

array([12, 15, 18])

In [63]:
A.sum(axis =1)          #rowwise

array([ 6, 15, 24])

In [64]:
A.mean(axis =0)

array([4., 5., 6.])

In [66]:
A.mean(axis =1)

array([2., 5., 8.])

In [67]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [68]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])